---
# tasks file for jenkins_casc

- name: Ensure /var/lib/jenkins/casc_configs directory exists
  file:
    path: /var/lib/jenkins/casc_configs
    state: directory
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"

- name: Copy Jenkins Configuration as Code (JCasC) file
  copy:
    src: jenkins_casc.yml
    dest: /var/lib/jenkins/casc_configs/jenkins.yaml
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: "0644"

- name: Set Jenkins environment variable for JCasC
  lineinfile:
    path: /etc/sysconfig/jenkins
    line: 'JENKINS_JAVA_OPTIONS="-Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=/var/lib/jenkins/casc_configs/jenkins.yaml"'
    create: yes
    state: present

- name: Jenkins config JCasC
  lineinfile: dest=/usr/lib/systemd/system/jenkins.service
    regexp='^Environment="JAVA_OPTS=-Djava.awt.headless=true'
    line='Environment="-Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=/var/lib/jenkins/casc_configs/jenkins.yaml"'
  register: result_skip_startup_wizard

- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: true
