jenkins:
  systemMessage: "Welcome to Jenkins configured by Code!"
  authorizationStrategy:
    projectMatrix:
      entries:
        - group:
            name: authenticated
            permissions:
              - Credentials/View
              - Job/Build
              - Job/Cancel
              - Job/Discover
              - Job/Read
              - Job/Workspace
              - Overall/Read
              - Run/Replay
              - View/Read
        - user:
            name: anonymous
            permissions:
              - Overall/Read
        - user:
            name: hieppm
            permissions:
              - Agent/Build
              - Agent/Configure
              - Agent/Connect
              - Agent/Create
              - Agent/Delete
              - Agent/Disconnect
              - Credentials/Create
              - Credentials/Delete
              - Credentials/ManageDomains
              - Credentials/Update
              - Credentials/View
              - Job/Build
              - Job/Cancel
              - Job/Configure
              - Job/Create
              - Job/Delete
              - Job/Discover
              - Job/Move
              - Job/Read
              - Job/Workspace
              - Overall/Administer
              - Overall/Read
              - Run/Delete
              - Run/Replay
              - Run/Update
              - View/Configure
              - View/Create
              - View/Delete
              - View/Read
        - user:
            name: admin
            permissions:
              - Agent/Build
              - Agent/Configure
              - Agent/Connect
              - Agent/Create
              - Agent/Delete
              - Agent/Disconnect
              - Credentials/Create
              - Credentials/Delete
              - Credentials/ManageDomains
              - Credentials/Update
              - Credentials/View
              - Job/Build
              - Job/Cancel
              - Job/Configure
              - Job/Create
              - Job/Delete
              - Job/Discover
              - Job/Move
              - Job/Read
              - Job/Workspace
              - Overall/Administer
              - Overall/Read
              - Run/Delete
              - Run/Replay
              - Run/Update
              - View/Configure
              - View/Create
              - View/Delete
              - View/Read
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "hieppm"
          password: "123456"
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 1
  slaveAgentPort: -1
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
  jobs:
    - script: >
        pipelineJob('job-seeder') {
          definition {
            cps {
              script("""
                pipeline {
                  agent any
                  stages {
                    stage('Checkout') {
                      steps {
                        git url: 'https://github.com/your-repo/your-dsl-repo.git', branch: 'main'
                      }
                    }
                    stage('Seed Jobs') {
                      steps {
                        jobDsl targets: 'scripts/jenkins-dsl/app/*.groovy', removedJobAction: 'ignore'
                      }
                    }
                  }
                }
              """)
              sandbox()
            }
          }
        }
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpPassword: "{AQAAABAAAAAQ9p6h/Sgk0zF7eCCk6ZRVyESg1jZzAn5afPqfR8vmM9g=}"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://jenkins:8080/github-webhook/"
  scmGit:
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
