---
# tasks file for install_java
- name: Install yum packages
  yum:
    name:
      - java-{{ java_version }}-openjdk
      - java-{{ java_version }}-openjdk-devel
      - git
    state: present

- name: Ensure Python is installed
  package:
    name: python3
    state: present

- name: Ensure pip is installed
  package:
    name: python3-pip
    state: present

- name: Ensure pip is upgraded to the latest version
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install Ansible via pip
  pip:
    name: ansible
    state: latest
    executable: pip3

# - name: Check if SSH key already exists
#   stat:
#     path: "{{ private_key_path }}"
#   register: private_key_stat

# - name: Generate SSH keypair if not exists
#   command: ssh-keygen -t rsa -b 2048 -f "{{ private_key_path }}" -N ""
#   when: private_key_stat.stat.exists == False

# - name: Print generated SSH public key
#   shell: cat "{{ public_key_path }}"
#   register: public_key
#   changed_when: false
#   when: private_key_stat.stat.exists == False

# - debug:
#     msg: "SSH key generated: {{ public_key.stdout }}"
#   when: private_key_stat.stat.exists == False

- include_tasks: "install_docker.yaml"
