---
# tasks file for install_java
- name: Install dependencies
  yum:
    name:
      - java-{{ java_version }}-openjdk
      - java-{{ java_version }}-openjdk-devel
      - git
    state: present

- include_tasks: "install_docker.yaml"
